calacademy-research/COMB

README.md
* adds an explanation of the COMB acronym
* wraps the YouTube video link in Markdown
* strips trailing whitespace
* escapes underscores
=> README tagline and nits

.gitignore, acoustic/data_ingest/src/readML.R, comb_functions.R
I added the readML.R script and changed the google drive folders to be in the COMB directory in google drive. I also cleaned up the script and made it more readable. I also added the comb_functions.R script which has a lot of custom functions that are used a lot.
=> Acoustic data ingest

point_counts/data_ingest/src/readPC.R, point_counts/naive_occupancy/src/naive_occ_plots.R, point_counts/naive_occupancy/src/naive_occupancy_17-21.R
Got this from https://github.com/calacademy-research/CAPLES/point_counts
Did the following: 
Adding a feature from a SOURCE repo (e.g. CAPLES) to a fork of a TARGET repo (the public COMB)
1. Forked the repo COMB to COMBddkapan on personal GitHub & clone from GitHub to your favorite place for git projects
```
cd ~/GitHub
git clone https://github.com/ddkapan/COMB COMBddkapan
```
2. Change directory to the local copy of CAPLES (the source repo)
```
cd ~/GitHub/CAPLES
```
3. Then split out the feature as a branch with the feature name as a subtree
```
git subtree split -P point_counts -b point_counts
```
4. Change directory to the COMBddkapan & make a feature branch
```
cd ~/GitHub/COMBddkapan
git branch point_counts
git checkout point_counts
```
5. Add the subtree to COMBddkapan
```
git …
```
=> Point counts

models/singleyr_occu_setup.R
Most data dependencies have been updated and work; however JAGS model will not run because updated environmental data are still needed (see issue "Remote sensing data outputs")
=> verified libraries and bird data dependencies working

acoustic/data_ingest/src/readML.R, acoustic/data_ingest/src/readML.subset.R, comb_functions.R
Additional minor updates to readML.R and added function logit_to_p in the comb_functions.R script.
=> Read ml.subset

acoustic/data_ingest/src/readML.subset.R, point_counts/data_ingest/src/readPC.R
some minor updates from branch jack_scratch; mostly some simple filtering and testing to help create outputs for the jags modeling...
=> Jack scratch

acoustic/csv_to_avro/src/csv_to_avro.py
This change makes the csv-to-avro pipline read birds.tsv instead of
birds.txt, with the difference being that the .tsv has unquoted fields.
This simplifies the parsing code. At the same time, it changes which
column of the .tsv is passed through to logit.key so that it is the
4-letter bird code rather than the 6-letter one.
For aru2point, it also makes the parsing silently skip any rows where
point is non numeric. Avro records resulting from such filenames are
still emitted with a null point submessage.
=> 4-letter bird codes in BigQuery

models/src/scratch_combined_model.R
* Reorders assignments to avoid any use before definition.
* Sorts library() statements alphabetically.
* Limits drive_sync to only strictly necessary folders
* Removes trailing whitespace
=> scratch_combined_model runnable from clean session

models/src/scratch_combined_model.R
Hoping for an easier merge....
=> style_file('scratch_combined_model.R')

DEVELOPING.md, acoustic/data_ingest/src/readML.R, acoustic/data_ingest/src/readML.subset.R, comb_functions.R, models/AHM/src/Chapter_5.MKC.R, models/AHM/src/Chapter_7.JPD.R, models/src/multiyr_occupancy_setup.R, models/src/scratch_combined_model.R, models/src/singleyr_occu_setup.R, point_counts/data_ingest/src/delintPC.R, point_counts/data_ingest/src/readPC.R, point_counts/naive_occupancy/src/naive_occ_plots.R, point_counts/naive_occupancy/src/naive_occupancy_17-21.R, spatial/src/scratch.R, spatial/src/tidyPCA.R, spatial_plots/src/SpatialPtCtPlots.R
Feel free to summarily reject this PR if you don't agree. It is polite proposal / demo, no semblance of a hard sell is intended:
A convention of always formatting .R sources with ```styler``` before committing them
The commit documents the rationale in DEVELOPING.md.
While there are many diff lines, they are all automated, as one could verify by running style_dir() in a local branch and "git diff"'ing that branch with this one.
=> Automated code formatting (proposal and base application)

models/src/combined.R
=> Remove score subsampling

models/src/readml.R
(no rush to review)
This PR is request for comment on the API for reading ML outputs and restructuring them for JAGS. Let me know if anything looks, e.g.: missing, wrong, unclear, hard-to-use...
If all looks OK, my plan is to make a separate PR for the implementation.
=> readml API

.gitignore, acoustic/data_ingest/src/readML.R, paper/note/read_first.Rmd, renv.lock, renv/activate.R, spatial/note/Caples_Spatial_EDA.Rmd, spatial/src/Tree_graphic_test.R, spatial/src/eda_forest_data_points.R, spatial/src/large_tree_demo.R, spatial/src/plot_pixel_comparison_tests_CH.R, spatial/src/read_adjust_combine_rasters.R, spatial/src/read_points_output_data.R, spatial/src/veg_plot_salo_comp.R, vegetation/note/PlotLevel_descriptions.Rmd
Intermediate (near final) satellite data crunching ... also a bit of Sarah's veg plot analysis +
Suggested changes to repo for workshop --> COMB > paper > note
Please approve since it won't stomp on anyone else's code.
=> Satellite 2 veg plot comparison

acoustic/data_ingest/src/readML.R
=> Read ml cleanup

models/src/posterior_pred_check.R
will need to be edited for efficiency (eg, renaming the sims.list object that goes into the code throughout so one won't have to change it during every iteration).
=> first code for post. pred checks

point_counts/data_ingest/src/delintPC.R
=> proofread for consistent AOU codes w/ readML

models/input/dataML_tall.csv, models/src/top3_pc_scores_veg.R
This runs if and only if points are removed from latlong.csv
397, 587, and 845, for which there are no point counts and which are too loud for ARUs
We can merge this, and I will concurrently upload an edited version of latlong.csv to
Resilience Data Drive/acoustic/data_ingest/input/latlong.csv
=> Top3 pc veg

models/src/combined.R, models/src/run_trials.R
I am proposing to merge this into main with minimal changes to the model currently in main.
When we eventually settle on the preferred form of the default model, then we can merge that into combined.R with the small changes needed to adapt it to the funtion(params) API.
Reviewers: please try your own test run and say whether it works or give feedback on the API.
When reading the code, I suggest setting the UI to ignore whitespace differences when looking at the diff.
=> Library for running JAGS over all species in parallel

models/input/dataML_top3.csv, models/src/top3_pc_scores_coverburn.R, models/src/top3_pc_scores_veg.R
@mschulist this is the most recent model lauren and I are working on-- it's on a uniquely named script so it can be merged to main if you want to pull it from there, or just pull directly from my branch!
=> adds burn severity covar

acoustic/spotcheck.R, models/src/comb_simulation.R, models/src/comb_simulation_MKC.R, models/src/combined_ko_allPC.R, models/src/combined_singleSp.R, models/src/empirical_explore.R, models/src/max_pc_scores_arubin_2covars_detcovars.R, models/src/max_pc_scores_arubin_3covars_2yrs.R, models/src/max_pc_scores_arubin_NOcovars_fileagg.R, models/src/mkc_figs.R, models/src/mkc_troubleshoot_burnvar.R, models/src/multi-year_explore.R, models/src/multiyear_no_ppc.R, models/src/threshold_expt.R, occupancy_plots.R
=> 115 paper figs
